models/BoxberryApi.php
<?php

namespace app\models;

use Yii;

/**
 * Boxberry Api
 *
 * @property string $url Адрес API
 * @property string $token Токен
 * @author ilya
 */
class BoxberryApi extends \yii\base\Model {
    
    
    private static function get($methodName, $params = [])
    {
        $url = Yii::$app->params['boxberryApiUrl']."?token=".Yii::$app->params['boxberryApiToken']."&method=".$methodName;
        foreach ($params as $key => $val) {
            $url .= "&".urlencode($key)."=".urlencode($val);
        }
        try {
            $data = file_get_contents($url);
            $result = json_decode($data);
            return $result;
        } catch (Exception $ex) {
            // TODO: обработка ошибок
        }
    }
    
    public static function ListCities()
    {
        return static::get('ListCities');
    }
    
    public static function DeliveryCosts($weight, $target, $orderSum = 0)
    {
        return static::get('DeliveryCosts', [
            'weight' => $weight,
            'target' => $target,
            'ordersum' => $orderSum
        ]);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii,
    yii\web\Controller,
    app\models\BoxberryApi;

class SiteController extends Controller
{

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        $cities = BoxberryApi::ListCities();
        return $this->render('index', [
            'cities' => $cities
        ]);
    }
    
    public function actionCalculate($weight, $target, $orderSum)
    {
        $weight = floatval($weight);
        $target = floatval($target);
        $orderSum = floatval($orderSum);
        
        if ($weight > 0 && $target > 0 && $orderSum >= 0) {
            $price = BoxberryApi::DeliveryCosts($weight, $target, $orderSum);
            return $this->render('result', [
                'price' => $price
            ]);
        } else {
            throw new \yii\base\Exception("Invalid params");
        }
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html,
    yii\helpers\ArrayHelper;

$this->title = 'Boxberry Calculator';
?>
<div class="site-index">
    <div class="body-content">
        <div class="row">
            <div class="col-lg-4">
                <?= Html::beginForm(['site/calculate'], 'get') ?>
                    <div class="form-group">
                        <label for="target">Город назначения</label>
                        <?=Html::dropDownList('target', 'target', ArrayHelper::map($cities, 'Code', 'Name'), ['id' => 'target', 'class' => 'form-control'])?>
                    </div>
                    <div class="form-group">
                        <label for="weight">Вес товара</label>
                        <?= Html::input('text', 'weight', '500', ['id' => 'weight', 'class' => 'form-control']) ?>
                        <p class="help-block">(в граммах)</p>
                    </div>
                    <div class="form-group">
                        <label for="orderSum">Стоимость товара</label>
                        <?= Html::input('text', 'orderSum', '0', ['id' => 'orderSum', 'class' => 'form-control']) ?>
                    </div>
                    <?= Html::submitButton('Рассчитать', ['class'=>'btn btn-default']) ?>
                <?= Html::endForm() ?>
            </div>
        </div>
    </div>
</div>

views/site/result.php
<?php
/* @var $this yii\web\View */
/* @var $price StdClass */

$this->title = 'Calculate result';
?>
<div class="site-calculate">
    <div class="body-content">
        <div class="row">
            <div class="col-lg-4">
                <h3>Результат:</h3>
                <p><strong>Стоимость:</strong> <?=$price->price?> руб.</p>
                <p><strong>Срок доставки:</strong> <?=$price->delivery_period?> дн.</p>
            </div>
        </div>
    </div>
</div>